name:  Murithi M'Inoti, Web Developer, UI/UX Enthusiast
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title: Karakana blog
email: ericmurithi@karakana.co.ke
description: >- # this means to ignore newlines until "baseurl:"
  Views on the internet & mobile technology and development.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Amurithi
github_username: emurithi
kramdown:
  input: GFM
  syntax_highlighter: rouge