name: Eric Murithi, Web Developer, UI/UX Enthusiast
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title: Karakana blog
email: ericmurithi@karakana.co.ke
description: >- Views on the internet & mobile technology and development
baseurl:""
twitter_username: amurithi
github_username: emurithi
